<?php

namespace {

    use SilverStripe\AssetAdmin\Forms\UploadField;
    use SilverStripe\Assets\Image;
    use SilverStripe\Forms\CheckboxField;
    use SilverStripe\Forms\DropdownField;
    use SilverStripe\Forms\HiddenField;
    use SilverStripe\Forms\HTMLEditor\HTMLEditorField;
    use SilverStripe\Forms\ReadonlyField;
    use SilverStripe\Forms\TextField;
    use SilverStripe\ORM\DataObject;

    class CardItem extends DataObject
    {
        private static $default_sort = 'Sort';

        private static $db = [
            'Name'       => 'Varchar',
            'CardIcon'   => 'Varchar',
            'Content'    => 'HTMLText',
            'CardWidth'  => 'Varchar',
            'Archived'   => 'Boolean',
            'Sort'       => 'Int'
        ];

        private static $has_one = [
            'Parent'=> Card::class,
            'Image' => Image::class
        ];

        private static $owns = [
            'Image'
        ];

        private static $summary_fields = [
            'Name',
            'Content.Summary' => 'Content summary',
            'CardWidth'       => 'Width',
            'Status'
        ];

        public function getCMSFields()
        {
            $fields = parent::getCMSFields(); // TODO: Change the autogenerated stub
            $fields->removeByName('ParentID');
            $fields->addFieldToTab('Root.Main', ReadonlyField::create('ParentRO', 'Parent', $this->Parent()->Title));
            $fields->addFieldToTab('Root.Main', TextField::create('Name'));
            $fields->addFieldToTab('Root.Main', TextField::create('CardIcon')
                ->setDescription('E.g fad fa-pills <br>Please refer&nbsp;<a href="https://fontawesome.com/v5.15/icons?d=gallery&p=2">FontAwesome</a>&nbsp;for more icon options.'));
            $fields->addFieldToTab('Root.Main', UploadField::create('Image')
                ->setFolderName('Sections/Card'));
            $fields->addFieldToTab('Root.Main', HTMLEditorField::create('Content'));
            $fields->addFieldToTab('Root.Main', DropdownField::create('CardWidth', 'Card width',
                SectionWidth::get()->filter('Archived', false)->map('Class', 'Name')));
            $fields->addFieldToTab('Root.Main', CheckboxField::create('Archived'));
            $fields->addFieldToTab('Root.Main', HiddenField::create('Sort'));

            return $fields;
        }

        public function getStatus()
        {
            if($this->Archived == 1) return _t('GridField.Archived', 'Archived');
            return _t('GridField.Live', 'Live');
        }
    }
}
