<?php

namespace {

    use SilverStripe\CMS\Model\SiteTree;
    use SilverStripe\Forms\CheckboxField;
    use SilverStripe\Forms\HiddenField;
    use SilverStripe\Forms\TextField;
    use SilverStripe\Forms\TreeDropdownField;
    use SilverStripe\ORM\DataObject;

    class PreHeaderMenu extends DataObject
    {
        private static $default_sort = 'Sort ASC';

        private static $db = [
            'Name'        => 'Varchar',
            'IconClass'   => 'Varchar',
            'ExternalURL' => 'Varchar',
            'Archived'    => 'Boolean',
            'Sort'        => 'Int',
        ];

        private static $has_one = [
            'Page' => SiteTree::class
        ];

        private static $summary_fields = [
            'Name',
            'Status'
        ];

        public function getCMSFields()
        {
            $fields = parent::getCMSFields(); // TODO: Change the autogenerated stub
            $fields->addFieldToTab('Root.Main', TextField::create('Name'));
            $fields->addFieldToTab('Root.Main', TreeDropdownField::create('PageID', 'Page link', SiteTree::class));
            $fields->addFieldToTab('Root.Main', TextField::create('ExternalURL', 'External url')
                ->setDescription('Only set when page link is not provided.'));
            $fields->addFieldToTab('Root.Main', TextField::create('IconClass')
                ->setDescription('E.g. fal fa-user-md <br>To find more icons, simply visit&nbsp;<a target="_blank" rel="nofollow" href="https://fontawesome.com/v5.15/icons?d=gallery&p=2">FontAwesome</a> website.'));
            $fields->addFieldToTab('Root.Main', CheckboxField::create('Archived'));
            $fields->addFieldToTab('Root.Main', HiddenField::create('Sort'));

            return $fields;
        }

        public function getStatus()
        {
            if($this->Archived == 1) return _t('GridField.Archived', 'Archived');
            return _t('GridField.Live', 'Live');
        }
    }
}
